### ISSUE TITLE
Next release version?

### ISSUE THREAD

**Issue by davejoyce** [osframework/confluent-kafka-go-ext#6]
The initial release version [v1.0.0](https://github.com/osframework/confluent-kafka-go-ext/releases/tag/v1.0.0) had 2 issues that were addressed in issue #4 and PR #5. The next release version will contain the fix but will also have a changed interface. Namely, the functions in `confluent/confluent.go` that raised [panic](https://golangdocs.com/panic-defer-recover-in-golang) on certain errors in v1.0.0 will now return an error instead.

This interface change is a "breaking" change from v1.0.0 - what should the next version be, following [semantic versioning](https://semver.org/)? 2.0.0?

**Comment by mknutty2** [comment]
OSS versions tend to start with smaller numbers (to include -SNAPSHOTS, etc) till they get the kinks worked out before it goes v1. 
Not sure if anyone besides the current audience is using this. So i  think either updating v1 or making v1.1 is fine.

**Comment by hudcoley** [comment]
Yeah I think keeping this v1 should be fine in this scenario. It's not really used at the moment and in golang, go mods treats v2+ differently than v0 or v1, so upgrading to something > v1 can be annoying

**Comment by davejoyce** [comment]
> OSS versions tend to start with smaller numbers (to include -SNAPSHOTS, etc) till they get the kinks worked out before it goes v1.

@mknutty2 you're right - I should have made the 1st release v0.0.1, as this is a brand new project that only has 1 known client project so far.

I think I generally agree with the pragmatic stance that everyone is taking here for this particular version. Understanding that subsequent versions may have a more "purist" adherence to semantic versioning.

I will cut the release branch as **v1.1.0**
